# Project Euler

# Problem 2

#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

library(tidyverse)

start <- proc.time()
i <- 2
f <- c(1,2)
while(sum(f[i-1],f[i-2]) < 4e6){
  aux = f[i-1] + f[i-2]
  f = c(f,aux)
  i = i + 1
}

f <- f %>%
  subset(. %% 2 == 0) %>%
  sum()
end <- proc.time()
print(end - start)



# End of File